name = "Optimization Base"
author = "Arty_x_g"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be1d73dd41853b059086840a1b66901ec3da6022eb06892c01cc68990bd85778"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"
