name = "Optimization Base"
author = "Arty_x_g"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c651910e3ec43f8b7591f3f429d02564dbed667dabd68708eb0e273ff32d7762"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"
